[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

# Adicione esta regra de redirecionamento abaixo
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200