[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

# Regra de redirecionamento para o React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Bloco de código para agendar a função keep-alive
[functions."keep-alive"]
  # A expressão cron "0 12 * * 1" significa:
  # Às 12:00 (meio-dia), toda Segunda-feira.
  schedule = "0 12 * * 1"